config/routes.rb
Rails.application.routes.draw do
  get 'statistics/show'
  resources :appointments, except: :show
  resources :doctors
  resources :patients

  root "patients#index"
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments, dependent: :destroy
    
    enum gender: { female: 'female', male: 'male'}
    #before_save :upcase_first_name, :upcase_last_name, :upcase_city

    validates :first_name, :last_name, :gender, :birth_date, :pesel, :city, presence: true
    validates :birth_date, comparison: { less_than_or_equal_to: Date.today, message: "Birth date cannot be greater than #{Date.today} (today)" }
    validates :pesel, uniqueness: true
    validates :pesel, format: { with: /\A\d{11}\z/, message: "must consist of eleven digits" }
    validates :first_name, :last_name, :city, format: { with: /\A\D*\z/, message: "cannot contain any digits" }

    def self.ransackable_attributes(auth_object = nil)
        ["birth_date", "gender", "last_name"]
    end

    def full_name
        "#{first_name.capitalize} #{last_name}"
    end

    def upcase_first_name
        self.first_name = self.first_name.upcase
    end

    def upcase_last_name
        self.last_name = self.last_name.upcase
    end

    def upcase_city
        self.city = self.city.upcase
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @q = Patient.ransack(params[:q])
    @patients = @q.result.page(params[:page])
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :gender, :birth_date, :pesel, :city)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <%= form.label :first_name, class: "form-field" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="form-row">
    <%= form.label :last_name, class: "form-field" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="form-row">
    <%= form.label :gender, class: "form-field" %>
    <%= collection_radio_buttons(:patient, :gender, Patient.genders, :first, :first, options: {}, html_options: { class: "mx-1" } ) %>
  </div>

  <div class="form-row">
    <%= form.label :birth_date, class: "form-field" %>
    <%= form.date_field :birth_date, :max => Date.today %>
  </div>

  <div class="form-row">
    <%= form.label :pesel, class: "form-field" %>
    <%= form.text_field :pesel %>
  </div>

  <div class="form-row">
    <%= form.label :city, class: "form-field" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/patients/_index_item.html.erb
<tr class="patient">
    <td class="patient-full-name"><%= patient.full_name %></td>
    <td class="patient-details"><%= patient.gender %></td>
    <td class="patient-details"><%= patient.birth_date %></td>
    <td class="patient-appointments">
        <%= count = patient.appointments.count
        count == 0 ? count : (link_to patient.appointments.count, appointments_path(patient_id: patient.id), data: { turbo: "false" }) %>
    </td>
    <td class="table-btns">
        <%= link_to "Show this patient", patient, data: { turbo: "false" }, class: "btn btn-secondary btn-sm" %>
        <%= new_appointment_button(patient, css_class: "btn btn-secondary btn-sm") %>
    </td>
</tr>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>First name:</strong>
    <%= patient.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= patient.last_name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= patient.gender %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= patient.birth_date %>
  </p>

  <p>
    <strong>Pesel:</strong>
    <%= patient.pesel %>
  </p>

  <p>
    <strong>City:</strong>
    <%= patient.city %>
  </p>

</div>

app/views/patients/_search.html.erb
<%= search_form_for @q, html: {"data-controller": "search", "data-turbo-frame": "table",
                                "class": "d-flex justify-content-around py-3 px-5 search_form"} do |f| %>
    <span>                                
        <%= f.label :last_name_cont %>
        <%= f.search_field :last_name_cont, "data-action": "search#submit", "class": "mx-2"  %>
    </span>
    <span>    
        <%= f.label(:gender_eq, "Gender:") %>
        <%= f.select :gender_eq, options_for_select([['both', ''], ['male'], ['female']], :selected => @q.gender_eq),
                                                    {}, {"data-action": "search#submit", "class": "mx-2" }  %>
    </span>
    <span>    
        <%= f.label(:birth_date_gt, "Birth date between:") %>
        <%= f.date_field :birth_date_gteq, "data-action": "search#submit", "class": "mx-2"  %>
  
        <%= f.label(:birth_date_lt, "and:") %>
        <%= f.date_field :birth_date_lt, "data-action": "search#submit", "class": "mx-2"  %>
    </span>

<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient, class: "btn btn-secondary" %> |
  <%= link_to "Back to patients", patients_path, class: "btn btn-secondary" %>
</div>

app/views/patients/index.html.erb
<div id="title-container", class="d-flex align-items-center title">
  <h1 class="mb-4 ml-5">Patients</h1>
  <%= button_to "Add new patient", new_patient_path, method: :get, class: "btn btn-secondary btn-lg mx-5 mb-4" %>
</div>

<%= render partial: 'search' %>

<%= turbo_frame_tag "table" do %>
  <div><%= paginate @patients %></div>
  <div id="patients" class="shadow border-b border-gray-200 bg-light bg-gradient">
    <table class="table table-striped table-hover rounded rounded-3 overflow-hidden">
      <thead class="bg-dark-gray text-white align-middle text-center">
        <tr>
          <th id="patient-name" scope="col" class="py-3 px-6">
            <span>
              Patient name
              <%= sort_link(@q, :last_name, default_order: :asc, class: "btn btn-light btn-sm mx-1") do %>
                <span></span>
              <% end %>
            </span>
          </th>
          <th id="patient-gender" scope="col" class="py-3 px-6">
            <span>Gender</span>
          </th>
          <th id="patient-birth-date" scope="col" class="py-3 px-6">
          <span>
            Birth date
            <%= sort_link(@q, :birth_date, default_order: :asc, class: "btn btn-light btn-sm mx-1") do %>
              <span></span>
            <% end %>
          </span>
          </th>
          <th id="patient-appointments" scope="col" class="py-3 px-6">
              <span>Number of appointments</span>
          </th>
          <th id="patient-acctions" scope="col" class="py-3 px-6">
            <span>Actions</span>
          </th>
        </tr>
      </thead>
      <tbody class="bg-light-gray align-middle text-center">
        <%= render partial: 'index_item', collection: @patients, as: :patient %>
      </tbody>
    </table>
  </div>
<% end %>  

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path, class: "btn btn-secondary" %>
</div>

app/views/patients/show.html.erb
<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient), class: "btn btn-secondary" %> |
  <%= link_to "Back to patients", patients_path, class: "btn btn-secondary" %>
  <div class="my-2">
    <%= button_to "Destroy this patient", @patient, method: :delete, class: "btn btn-secondary" %>
  </div>
</div>