config/routes.rb
Rails.application.routes.draw do
  get 'statistics/show'
  resources :appointments, except: :show
  resources :doctors
  resources :patients

  root "patients#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    
    validates :first_name, :last_name,  presence: true
    validates :first_name, :last_name, format: { with: /\A\D*\z/, message: "cannot contain any digits" }

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.order(:last_name).page(params[:page])
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>First name:</strong>
    <%= doctor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= doctor.last_name %>
  </p>

  <p>
    <strong>Number of appointments:</strong>
    <%= count = doctor.appointments.count
        count == 0 ? count : (link_to doctor.appointments.count, appointments_path(doctor_id: doctor.id)) %>
  </p>

</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <%= form.label :first_name, class: "form-field" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="form-row">
    <%= form.label :last_name, class: "form-field" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/doctors/_index_item.html.erb
<tr class="doctor">
    <td class="doctor-full-name"><%= doctor.full_name %></td>
    <td class="doctor-appointments">
        <%= count = doctor.appointments.count
        count == 0 ? count : (link_to doctor.appointments.count, appointments_path(doctor_id: doctor.id), data: { turbo: "false" }) %>
    </td>
    <td class="table-btns">
        <%= link_to "Show this doctor", doctor, data: { turbo: "false" }, class: "btn btn-secondary btn-sm" %>
    </td>
</tr>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Show this doctor", @doctor, class: "btn btn-secondary" %> |
  <%= link_to "Back to doctors", doctors_path, class: "btn btn-secondary" %>
</div>

app/views/doctors/index.html.erb
<div id="title-container", class="d-flex align-items-center title">
  <h1 class="mb-4 ml-5">Doctors</h1>
  <%= button_to "Add new doctor", new_doctor_path, method: :get, class: "btn btn-secondary btn-lg mx-5 mb-4" %>
</div>


<%= turbo_frame_tag "table" do %>
  <div><%= paginate @doctors %></div>
  <div id="doctors" class="shadow border-b border-gray-200 bg-light bg-gradient">
    <table class="table table-striped table-hover rounded rounded-3 overflow-hidden">
      <thead class="bg-dark-gray text-white align-middle text-center">
        <tr>
          <th id="doctor-name" scope="col" class="py-3 px-6">
            <span>Doctor name</span>
          </th>
          <th id="doctor-appointments" scope="col" class="py-3 px-6">
              <span>Number of appointments</span>
          </th>
          <th id="doctor-actions" scope="col" class="py-3 px-6">
            <span>Actions</span>
          </th>
        </tr>
      </thead>
      <tbody class="bg-light-gray align-middle text-center">
        <%= render partial: 'index_item', collection: @doctors, as: :doctor %>
      </tbody>
    </table>
  </div>
<% end %>  

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Back to doctors", doctors_path, class: "btn btn-secondary" %>
</div>

app/views/doctors/show.html.erb
<%= render @doctor %>

<div>
  <%= link_to "Edit this doctor", edit_doctor_path(@doctor), class: "btn btn-secondary" %> |
  <%= link_to "Back to doctors", doctors_path, class: "btn btn-secondary" %>
  <div class="my-2">
    <%= button_to "Destroy this doctor", @doctor, method: :delete, class: "btn btn-secondary" %>
  </div>
</div>