config/routes.rb
Rails.application.routes.draw do
  get 'statistics/show'
  resources :appointments, except: :show
  resources :doctors
  resources :patients

  root "patients#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatClinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body>
    <nav class="navbar navbar-expand-lg navbar-light p-0">
      <div class="container-fluid">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'MatClinic logo', class: 'logo' %>
        <% end %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Patients', patients_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Appointments', appointments_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Doctors', doctors_path, class: 'navbar-brand' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Statistics', statistics_show_path, class: 'navbar-brand' %>
            </li>
          </ul>
      </div>
    </nav>
      
    <div class="container mb-5">
      <% flash.each do |type, msg| %>
        <%= tag.div msg, class: "alert alert-#{type == 'alert' ? 'danger' : 'success'}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>